import type { CodeGraph } from "@core/graph";
import { buildModule, buildSteps, edge, latency } from "../lib/build";
import type { DemoDefinition } from "../types";

const ORDERS_API = "gateway/orders_controller.ts";
const ORDER_SERVICE = "services/orders/order_service.ts";
const ORDERS_REPO = "services/orders/orders_repository.ts";
const OUTBOX = "services/orders/outbox_publisher.ts";
const TOPIC = "infra/kafka/orders_created_topic.ts";
const BILLING = "services/billing/billing_consumer.py";
const PAYMENT_CLIENT = "services/billing/payment_client.py";
const PAYMENTS = "services/payments/payments_server.go";
const STOCK_JOB = "services/inventory/stock_job.scala";
const STOCK_CACHE = "services/inventory/stock_cache.ts";
const ANALYTICS = "services/analytics/clickhouse_sink.ts";

const graph: CodeGraph = {
  version: 1,
  projectName: "Demo · Tienda event-driven (Kafka + gRPC)",
  groups: [
    { id: "gateway", label: "Gateway", color: "sky" },
    { id: "orders", label: "Pedidos", color: "violet" },
    { id: "kafka", label: "Kafka", color: "rose" },
    { id: "billing", label: "Facturación", color: "amber" },
    { id: "inventory", label: "Inventario", color: "emerald" },
    { id: "analytics", label: "Analítica", color: "zinc" },
  ],
  subsystems: [
    { id: "messaging", label: "Kafka · orders.created", color: "rose" },
    { id: "payments", label: "Pagos · gRPC", color: "sky" },
    { id: "data", label: "Datos · Postgres, Redis, ClickHouse", color: "emerald" },
  ],
  modules: [
    buildModule({
      id: ORDERS_API,
      label: "Orders API",
      groupId: "gateway",
      role: "api",
      layer: 0,
      summary: "POST /orders: valida el pedido y lo delega al servicio de pedidos.",
      blocks: [["createOrder", 14, 41, "Valida body (sku, qty) y responde 202 con el id del pedido."]],
    }),
    buildModule({
      id: ORDER_SERVICE,
      label: "Order Service",
      groupId: "orders",
      role: "service",
      layer: 3,
      summary: "Lógica de pedidos: persiste el pedido y registra el evento en la outbox en la misma transacción.",
      blocks: [["OrderService", 8, 64], ["OrderService.place", 20, 58, "INSERT pedido + outbox en una transacción."]],
    }),
    buildModule({
      id: ORDERS_REPO,
      label: "Orders Repository",
      groupId: "orders",
      role: "database",
      layer: 2,
      subsystem: "data",
      summary: "Acceso a Postgres (tabla orders y outbox) con pg.",
      blocks: [["insertOrder", 10, 33, "INSERT INTO orders … RETURNING id."]],
    }),
    buildModule({
      id: OUTBOX,
      label: "Outbox Publisher",
      groupId: "orders",
      role: "broker",
      layer: 2,
      subsystem: "messaging",
      summary: "Lee la outbox y publica cada fila en el topic orders.created (kafkajs, idempotente).",
      blocks: [["publishPending", 12, 47, "producer.send({ topic: 'orders.created', messages })."]],
    }),
    buildModule({
      id: TOPIC,
      label: "Topic orders.created",
      groupId: "kafka",
      role: "broker",
      layer: 2,
      subsystem: "messaging",
      summary: "Declaración del topic: 6 particiones por orderId, retención 7 días.",
      blocks: [["ORDERS_CREATED", 3, 18, "partitions: 6 · key: orderId · retention: 7d."]],
    }),
    buildModule({
      id: BILLING,
      label: "Billing Consumer",
      groupId: "billing",
      role: "broker",
      layer: 2,
      subsystem: "messaging",
      summary: "Consumer group «billing»: por cada pedido crea la factura y cobra vía gRPC.",
      blocks: [["handle_order_created", 15, 52, "Deserializa el evento y llama a Payments.Charge."]],
    }),
    buildModule({
      id: PAYMENT_CLIENT,
      label: "Payment Client",
      groupId: "billing",
      role: "rpc",
      layer: 2,
      subsystem: "payments",
      summary: "Stub gRPC del servicio Payments con reintentos y deadline de 2 s.",
      blocks: [["charge", 9, 30, "PaymentsStub(channel).Charge(ChargeRequest)."]],
    }),
    buildModule({
      id: PAYMENTS,
      label: "Payments Server",
      groupId: "billing",
      role: "rpc",
      layer: 2,
      subsystem: "payments",
      summary: "Servidor gRPC en Go: autoriza el cobro contra la pasarela y devuelve el estado.",
      blocks: [["Server", 14, 64], ["Server.Charge", 22, 61, "Autoriza el cobro y devuelve ChargeReply{status}."]],
    }),
    buildModule({
      id: STOCK_JOB,
      label: "Stock Job (Flink)",
      groupId: "inventory",
      role: "stream",
      layer: 1,
      summary: "Job de Flink: consume orders.created, descuenta stock por SKU en ventanas de 5 s.",
      blocks: [["StockJob", 7, 58], ["StockJob.run", 12, 55, "keyBy(sku).window(5s).reduce(sum(qty))."]],
    }),
    buildModule({
      id: STOCK_CACHE,
      label: "Stock Cache",
      groupId: "inventory",
      role: "cache",
      layer: 2,
      subsystem: "data",
      summary: "Stock disponible por SKU en Redis (lecturas del catálogo en ~1 ms).",
      blocks: [["decrementStock", 6, 24, "DECRBY stock:<sku> qty."]],
    }),
    buildModule({
      id: ANALYTICS,
      label: "Analytics Sink",
      groupId: "analytics",
      role: "database",
      layer: 2,
      subsystem: "data",
      summary: "Inserta ventas agregadas en ClickHouse para los paneles de negocio.",
      blocks: [["insertSales", 8, 29, "INSERT INTO sales_5s (sku, qty, ts)."]],
    }),
  ],
  edges: [
    edge(ORDERS_API, ORDER_SERVICE, "calls", "place()"),
    edge(ORDER_SERVICE, ORDERS_REPO, "calls", "INSERT"),
    edge(ORDER_SERVICE, OUTBOX, "calls", "outbox"),
    edge(OUTBOX, TOPIC, "data-flow", "orders.created"),
    edge(TOPIC, BILLING, "data-flow", "orders.created"),
    edge(TOPIC, STOCK_JOB, "data-flow", "orders.created"),
    edge(BILLING, PAYMENT_CLIENT, "calls", "charge()"),
    edge(PAYMENT_CLIENT, PAYMENTS, "calls", "gRPC Payments"),
    edge(STOCK_JOB, STOCK_CACHE, "data-flow", "stock"),
    edge(STOCK_JOB, ANALYTICS, "data-flow", "ventas"),
  ],
};

const ORDER = { orderId: "A-1042", customerId: "c-77", items: [{ sku: "BOOK-7", qty: 2 }], total: 39.8 };
const EVENT = { type: "order.created", orderId: "A-1042", items: ORDER.items, ts: "2026-09-27T10:15:02Z" };

export const EVENT_DRIVEN_SHOP_DEMO: DemoDefinition = {
  graphName: "demo_event_shop",
  title: "Tienda event-driven",
  tagline: "Microservicios con Kafka, gRPC, Flink, Postgres, Redis y ClickHouse",
  graph,
  scenarios: {
    version: 1,
    graph: "demo_event_shop",
    scenarios: [
      {
        id: "order-to-payment",
        name: "Del pedido al cobro",
        description: "Un POST /orders se guarda con outbox, viaja por Kafka y termina cobrado por gRPC.",
        entryNodeId: ORDERS_API,
        steps: buildSteps(graph, [
          {
            nodeId: ORDERS_API,
            block: "createOrder",
            title: "Llega el pedido",
            description: "La API valida el body y lo delega; responde 202 sin esperar al cobro.",
            input: ORDER,
            output: { status: 202, orderId: ORDER.orderId },
            metrics: latency(14, { httpStatus: 202 }),
          },
          {
            nodeId: ORDER_SERVICE,
            block: "OrderService.place",
            title: "Pedido + outbox en una transacción",
            description: "Patrón outbox: el evento no se pierde aunque Kafka esté caído en ese momento.",
            input: ORDER,
            output: { orderId: ORDER.orderId, outbox: 1 },
            metrics: latency(9),
          },
          {
            nodeId: ORDERS_REPO,
            block: "insertOrder",
            title: "Postgres guarda el pedido",
            description: "INSERT en orders y outbox dentro de la misma transacción.",
            input: { table: "orders", rows: 1 },
            output: { id: ORDER.orderId },
            metrics: latency(23, { rows: 2 }),
          },
          {
            nodeId: OUTBOX,
            block: "publishPending",
            title: "Se publica el evento",
            description: "La outbox publica en orders.created con key=orderId (mismo pedido → misma partición).",
            input: { pending: 1 },
            output: EVENT,
            metrics: latency(6, { partitions: 6 }),
          },
          {
            nodeId: TOPIC,
            block: "ORDERS_CREATED",
            title: "Kafka reparte el evento",
            description: "Cada consumer group recibe su copia: facturación e inventario avanzan en paralelo.",
            input: EVENT,
            output: { partition: 3, offset: 91822 },
            metrics: latency(4, { consumerLagMs: 35 }),
          },
          {
            nodeId: BILLING,
            block: "handle_order_created",
            title: "Facturación consume",
            description: "El consumer group «billing» deserializa el evento y pide el cobro.",
            input: EVENT,
            output: { invoice: "F-2026-3310" },
            metrics: latency(18, { consumerLagMs: 35 }),
          },
          {
            nodeId: PAYMENT_CLIENT,
            block: "charge",
            title: "Llamada gRPC",
            description: "El stub llama a Payments.Charge con deadline de 2 s y reintento idempotente.",
            input: { orderId: ORDER.orderId, amount: ORDER.total },
            output: { rpc: "Payments.Charge" },
            metrics: latency(3),
          },
          {
            nodeId: PAYMENTS,
            block: "Server.Charge",
            title: "Pagos autoriza",
            description: "El servidor Go autoriza contra la pasarela y responde el estado.",
            input: { orderId: ORDER.orderId, amount: ORDER.total },
            output: { status: "AUTHORIZED" },
            metrics: latency(120, { grpcCode: 0 }),
            durationMs: 2400,
          },
        ]),
      },
      {
        id: "order-to-stock",
        name: "Del evento al stock y la analítica",
        description: "El mismo evento, en paralelo: Flink descuenta stock en Redis y agrega ventas en ClickHouse.",
        entryNodeId: TOPIC,
        steps: buildSteps(graph, [
          {
            nodeId: TOPIC,
            block: "ORDERS_CREATED",
            title: "El evento está en el topic",
            description: "El consumer group del job de Flink lee su propia copia.",
            input: EVENT,
            output: { partition: 3, offset: 91822 },
            metrics: latency(4),
          },
          {
            nodeId: STOCK_JOB,
            block: "StockJob.run",
            title: "Flink agrega por SKU",
            description: "keyBy(sku) + ventana de 5 s: muchas unidades del mismo libro se descuentan en una escritura.",
            input: EVENT,
            output: { sku: "BOOK-7", qty: 2, window: "10:15:00–10:15:05" },
            metrics: latency(45, { windowMs: 5000 }),
          },
          {
            nodeId: STOCK_CACHE,
            block: "decrementStock",
            title: "Redis descuenta stock",
            description: "DECRBY atómico: el catálogo ve el stock nuevo al instante.",
            input: { key: "stock:BOOK-7", by: 2 },
            output: { stock: 118 },
            metrics: latency(1.2),
          },
          {
            nodeId: STOCK_JOB,
            block: "StockJob.run",
            title: "La misma ventana va a analítica",
            description: "El job emite también el agregado de ventas para los paneles.",
            input: { sku: "BOOK-7", qty: 2 },
            output: { rows: 1 },
            metrics: latency(3),
          },
          {
            nodeId: ANALYTICS,
            block: "insertSales",
            title: "ClickHouse guarda la venta",
            description: "INSERT por lotes en sales_5s; los paneles lo ven en el siguiente refresco.",
            input: { table: "sales_5s", rows: 1 },
            output: { inserted: 1 },
            metrics: latency(12, { rows: 1 }),
          },
        ]),
      },
    ],
  },
  trace: {
    profile: "event",
    entryNodeId: OUTBOX,
    payload: JSON.stringify(EVENT, null, 2),
  },
};
